[upscale]
enable_upscale = false
upscale_minsize = 1920
realesrgan_model = "RealESRGAN_x4plus"
realesrgan_model_path = "sd-models/RealESRGAN/RealESRGAN_x4plus.pth"
outscale = 2
min_side = 768
max_side = 1024
[face_enhance]
enablce_face_enhance = true
weight = 0.5
face_crop= true
face_crop_resize= 1024
enable_upscale = false
realesrgan_model = "RealESRGAN_x4plus"
realesrgan_model_path = "sd-models/RealESRGAN/RealESRGAN_x4plus.pth"
outscale = 1
[segbody]
enable_segbody = false
ali_ak = ""
ali_sk = ""
ali_endpoint = ""
ali_region = ""
[cropface]
enable_cropface = false

[tag]
tag_type = "tag"
florence_task = "detailed_caption"
filter_tags_keywords = "eye,ear,cheek,tooth,nose,transparent_background"
added_fixed_tags="simple_background,white_background"